#!/usr/bin/env python

import sys
from os.path import join, dirname, realpath

afn_path = dirname(realpath(__file__))

sys.path.append(join(afn_path, "src"))

from autobus2.tools import autosend
autosend.main()

