#!/usr/bin/env python

import sys
from os.path import join, dirname, realpath

afn_path = dirname(realpath(__file__))

sys.path.append(join(afn_path, "src"))

exec open(join(afn_path, "src", "autosend.py"))

