#!/usr/bin/env python

import time

with open("setup.py") as input:
    lines = list(input)
with open("setup.py.2", "w") as out:
    for line in lines:
        if "# !!!VERSION!!!" in line:
            line = 'version = "0.1.%s" # !!!VERSION!!!\n' % time.strftime("%Y.%m.%d")
        out.write(line)

