# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2



_MAPENTRY = descriptor.Descriptor(
  name='MapEntry',
  full_name='MapEntry',
  filename='autobus.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='key', full_name='MapEntry.key', index=0,
      number=1, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='MapEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_STRUCTENTRY = descriptor.Descriptor(
  name='StructEntry',
  full_name='StructEntry',
  filename='autobus.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='key', full_name='StructEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='StructEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_INSTANCE = descriptor.Descriptor(
  name='Instance',
  full_name='Instance',
  filename='autobus.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='value1', full_name='Instance.value1', index=0,
      number=1, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value2', full_name='Instance.value2', index=1,
      number=2, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value3', full_name='Instance.value3', index=2,
      number=3, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value4', full_name='Instance.value4', index=3,
      number=4, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value5', full_name='Instance.value5', index=4,
      number=5, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value6', full_name='Instance.value6', index=5,
      number=6, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value7', full_name='Instance.value7', index=6,
      number=7, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value8', full_name='Instance.value8', index=7,
      number=8, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value9', full_name='Instance.value9', index=8,
      number=9, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value10', full_name='Instance.value10', index=9,
      number=10, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value11', full_name='Instance.value11', index=10,
      number=11, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value_n', full_name='Instance.value_n', index=11,
      number=100, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_INTEGERINSTANCE = descriptor.Descriptor(
  name='IntegerInstance',
  full_name='IntegerInstance',
  filename='autobus.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='value', full_name='IntegerInstance.value', index=0,
      number=1, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_LONGINSTANCE = descriptor.Descriptor(
  name='LongInstance',
  full_name='LongInstance',
  filename='autobus.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='value', full_name='LongInstance.value', index=0,
      number=1, type=3, cpp_type=2, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_DOUBLEINSTANCE = descriptor.Descriptor(
  name='DoubleInstance',
  full_name='DoubleInstance',
  filename='autobus.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='value', full_name='DoubleInstance.value', index=0,
      number=1, type=1, cpp_type=5, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_STRINGINSTANCE = descriptor.Descriptor(
  name='StringInstance',
  full_name='StringInstance',
  filename='autobus.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='value', full_name='StringInstance.value', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_TIMESTAMPINSTANCE = descriptor.Descriptor(
  name='TimestampInstance',
  full_name='TimestampInstance',
  filename='autobus.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='year', full_name='TimestampInstance.year', index=0,
      number=1, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='month', full_name='TimestampInstance.month', index=1,
      number=2, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='day', full_name='TimestampInstance.day', index=2,
      number=3, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='hour', full_name='TimestampInstance.hour', index=3,
      number=4, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='minute', full_name='TimestampInstance.minute', index=4,
      number=5, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='second', full_name='TimestampInstance.second', index=5,
      number=6, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='millisecond', full_name='TimestampInstance.millisecond', index=6,
      number=7, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_NULLINSTANCE = descriptor.Descriptor(
  name='NullInstance',
  full_name='NullInstance',
  filename='autobus.proto',
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_LISTINSTANCE = descriptor.Descriptor(
  name='ListInstance',
  full_name='ListInstance',
  filename='autobus.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='value', full_name='ListInstance.value', index=0,
      number=1, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_MAPINSTANCE = descriptor.Descriptor(
  name='MapInstance',
  full_name='MapInstance',
  filename='autobus.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='value', full_name='MapInstance.value', index=0,
      number=1, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_STRUCTINSTANCE = descriptor.Descriptor(
  name='StructInstance',
  full_name='StructInstance',
  filename='autobus.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='StructInstance.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='StructInstance.value', index=1,
      number=2, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_EXCEPTIONINSTANCE = descriptor.Descriptor(
  name='ExceptionInstance',
  full_name='ExceptionInstance',
  filename='autobus.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='text', full_name='ExceptionInstance.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_BOOLINSTANCE = descriptor.Descriptor(
  name='BoolInstance',
  full_name='BoolInstance',
  filename='autobus.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='value', full_name='BoolInstance.value', index=0,
      number=1, type=8, cpp_type=7, label=2,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_MESSAGE = descriptor.Descriptor(
  name='Message',
  full_name='Message',
  filename='autobus.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='message_type', full_name='Message.message_type', index=0,
      number=1, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='message_id', full_name='Message.message_id', index=1,
      number=60, type=3, cpp_type=2, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value2', full_name='Message.value2', index=2,
      number=2, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value3', full_name='Message.value3', index=3,
      number=3, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value4', full_name='Message.value4', index=4,
      number=4, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value5', full_name='Message.value5', index=5,
      number=5, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value6', full_name='Message.value6', index=6,
      number=6, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value7', full_name='Message.value7', index=7,
      number=7, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value8', full_name='Message.value8', index=8,
      number=8, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value9', full_name='Message.value9', index=9,
      number=9, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value10', full_name='Message.value10', index=10,
      number=10, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value11', full_name='Message.value11', index=11,
      number=11, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value12', full_name='Message.value12', index=12,
      number=12, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value13', full_name='Message.value13', index=13,
      number=13, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value14', full_name='Message.value14', index=14,
      number=14, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value15', full_name='Message.value15', index=15,
      number=15, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value16', full_name='Message.value16', index=16,
      number=16, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value17', full_name='Message.value17', index=17,
      number=17, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value19', full_name='Message.value19', index=18,
      number=19, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value20', full_name='Message.value20', index=19,
      number=20, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value21', full_name='Message.value21', index=20,
      number=21, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value22', full_name='Message.value22', index=21,
      number=22, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value23', full_name='Message.value23', index=22,
      number=23, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value24', full_name='Message.value24', index=23,
      number=24, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value25', full_name='Message.value25', index=24,
      number=25, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value_n', full_name='Message.value_n', index=25,
      number=100, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_REGISTERINTERFACECOMMAND = descriptor.Descriptor(
  name='RegisterInterfaceCommand',
  full_name='RegisterInterfaceCommand',
  filename='autobus.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='RegisterInterfaceCommand.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='doc', full_name='RegisterInterfaceCommand.doc', index=1,
      number=3, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_REGISTERINTERFACERESPONSE = descriptor.Descriptor(
  name='RegisterInterfaceResponse',
  full_name='RegisterInterfaceResponse',
  filename='autobus.proto',
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_REGISTERFUNCTIONCOMMAND = descriptor.Descriptor(
  name='RegisterFunctionCommand',
  full_name='RegisterFunctionCommand',
  filename='autobus.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='interface_name', full_name='RegisterFunctionCommand.interface_name', index=0,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='name', full_name='RegisterFunctionCommand.name', index=1,
      number=3, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='doc', full_name='RegisterFunctionCommand.doc', index=2,
      number=4, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_REGISTERFUNCTIONRESPONSE = descriptor.Descriptor(
  name='RegisterFunctionResponse',
  full_name='RegisterFunctionResponse',
  filename='autobus.proto',
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_CALLFUNCTIONCOMMAND = descriptor.Descriptor(
  name='CallFunctionCommand',
  full_name='CallFunctionCommand',
  filename='autobus.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='interface_name', full_name='CallFunctionCommand.interface_name', index=0,
      number=2, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='function', full_name='CallFunctionCommand.function', index=1,
      number=3, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='arguments', full_name='CallFunctionCommand.arguments', index=2,
      number=4, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_CALLFUNCTIONRESPONSE = descriptor.Descriptor(
  name='CallFunctionResponse',
  full_name='CallFunctionResponse',
  filename='autobus.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='return_value', full_name='CallFunctionResponse.return_value', index=0,
      number=1, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_RUNFUNCTIONCOMMAND = descriptor.Descriptor(
  name='RunFunctionCommand',
  full_name='RunFunctionCommand',
  filename='autobus.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='interface_name', full_name='RunFunctionCommand.interface_name', index=0,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='function', full_name='RunFunctionCommand.function', index=1,
      number=3, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='arguments', full_name='RunFunctionCommand.arguments', index=2,
      number=4, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_RUNFUNCTIONRESPONSE = descriptor.Descriptor(
  name='RunFunctionResponse',
  full_name='RunFunctionResponse',
  filename='autobus.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='return_value', full_name='RunFunctionResponse.return_value', index=0,
      number=1, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_ERRORRESPONSE = descriptor.Descriptor(
  name='ErrorResponse',
  full_name='ErrorResponse',
  filename='autobus.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='text', full_name='ErrorResponse.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_REGISTEREVENTCOMMAND = descriptor.Descriptor(
  name='RegisterEventCommand',
  full_name='RegisterEventCommand',
  filename='autobus.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='interface_name', full_name='RegisterEventCommand.interface_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='event_name', full_name='RegisterEventCommand.event_name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='doc', full_name='RegisterEventCommand.doc', index=2,
      number=3, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_REGISTEREVENTRESPONSE = descriptor.Descriptor(
  name='RegisterEventResponse',
  full_name='RegisterEventResponse',
  filename='autobus.proto',
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_REGISTERLISTENERCOMMAND = descriptor.Descriptor(
  name='RegisterListenerCommand',
  full_name='RegisterListenerCommand',
  filename='autobus.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='interface_name', full_name='RegisterListenerCommand.interface_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='event_name', full_name='RegisterListenerCommand.event_name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_REGISTERLISTENERRESPONSE = descriptor.Descriptor(
  name='RegisterListenerResponse',
  full_name='RegisterListenerResponse',
  filename='autobus.proto',
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_DEREGISTERLISTENERCOMMAND = descriptor.Descriptor(
  name='DeregisterListenerCommand',
  full_name='DeregisterListenerCommand',
  filename='autobus.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='interface_name', full_name='DeregisterListenerCommand.interface_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='event_name', full_name='DeregisterListenerCommand.event_name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_DEREGISTERLISTENERRESPONSE = descriptor.Descriptor(
  name='DeregisterListenerResponse',
  full_name='DeregisterListenerResponse',
  filename='autobus.proto',
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_FIREEVENTCOMMAND = descriptor.Descriptor(
  name='FireEventCommand',
  full_name='FireEventCommand',
  filename='autobus.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='interface_name', full_name='FireEventCommand.interface_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='event_name', full_name='FireEventCommand.event_name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='arguments', full_name='FireEventCommand.arguments', index=2,
      number=4, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_REGISTEROBJECTCOMMAND = descriptor.Descriptor(
  name='RegisterObjectCommand',
  full_name='RegisterObjectCommand',
  filename='autobus.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='interface_name', full_name='RegisterObjectCommand.interface_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='object_name', full_name='RegisterObjectCommand.object_name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='doc', full_name='RegisterObjectCommand.doc', index=2,
      number=3, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='RegisterObjectCommand.value', index=3,
      number=4, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_REGISTEROBJECTRESPONSE = descriptor.Descriptor(
  name='RegisterObjectResponse',
  full_name='RegisterObjectResponse',
  filename='autobus.proto',
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_WATCHOBJECTCOMMAND = descriptor.Descriptor(
  name='WatchObjectCommand',
  full_name='WatchObjectCommand',
  filename='autobus.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='interface_name', full_name='WatchObjectCommand.interface_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='object_name', full_name='WatchObjectCommand.object_name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_WATCHOBJECTRESPONSE = descriptor.Descriptor(
  name='WatchObjectResponse',
  full_name='WatchObjectResponse',
  filename='autobus.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='value', full_name='WatchObjectResponse.value', index=0,
      number=1, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_UNWATCHOBJECTCOMMAND = descriptor.Descriptor(
  name='UnwatchObjectCommand',
  full_name='UnwatchObjectCommand',
  filename='autobus.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='interface_name', full_name='UnwatchObjectCommand.interface_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='object_name', full_name='UnwatchObjectCommand.object_name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_UNWATCHOBJECTRESPONSE = descriptor.Descriptor(
  name='UnwatchObjectResponse',
  full_name='UnwatchObjectResponse',
  filename='autobus.proto',
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_SETOBJECTCOMMAND = descriptor.Descriptor(
  name='SetObjectCommand',
  full_name='SetObjectCommand',
  filename='autobus.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='interface_name', full_name='SetObjectCommand.interface_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='object_name', full_name='SetObjectCommand.object_name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='SetObjectCommand.value', index=2,
      number=4, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_MAPENTRY.fields_by_name['key'].message_type = _INSTANCE
_MAPENTRY.fields_by_name['value'].message_type = _INSTANCE
_STRUCTENTRY.fields_by_name['value'].message_type = _INSTANCE
_INSTANCE.fields_by_name['value1'].message_type = _INTEGERINSTANCE
_INSTANCE.fields_by_name['value2'].message_type = _LONGINSTANCE
_INSTANCE.fields_by_name['value3'].message_type = _DOUBLEINSTANCE
_INSTANCE.fields_by_name['value4'].message_type = _STRINGINSTANCE
_INSTANCE.fields_by_name['value5'].message_type = _TIMESTAMPINSTANCE
_INSTANCE.fields_by_name['value6'].message_type = _NULLINSTANCE
_INSTANCE.fields_by_name['value7'].message_type = _LISTINSTANCE
_INSTANCE.fields_by_name['value8'].message_type = _MAPINSTANCE
_INSTANCE.fields_by_name['value9'].message_type = _STRUCTINSTANCE
_INSTANCE.fields_by_name['value10'].message_type = _EXCEPTIONINSTANCE
_INSTANCE.fields_by_name['value11'].message_type = _BOOLINSTANCE
_LISTINSTANCE.fields_by_name['value'].message_type = _INSTANCE
_MAPINSTANCE.fields_by_name['value'].message_type = _MAPENTRY
_STRUCTINSTANCE.fields_by_name['value'].message_type = _STRUCTENTRY
_MESSAGE.fields_by_name['value2'].message_type = _REGISTERINTERFACECOMMAND
_MESSAGE.fields_by_name['value3'].message_type = _REGISTERINTERFACERESPONSE
_MESSAGE.fields_by_name['value4'].message_type = _REGISTERFUNCTIONCOMMAND
_MESSAGE.fields_by_name['value5'].message_type = _REGISTERFUNCTIONRESPONSE
_MESSAGE.fields_by_name['value6'].message_type = _CALLFUNCTIONCOMMAND
_MESSAGE.fields_by_name['value7'].message_type = _CALLFUNCTIONRESPONSE
_MESSAGE.fields_by_name['value8'].message_type = _RUNFUNCTIONCOMMAND
_MESSAGE.fields_by_name['value9'].message_type = _RUNFUNCTIONRESPONSE
_MESSAGE.fields_by_name['value10'].message_type = _ERRORRESPONSE
_MESSAGE.fields_by_name['value11'].message_type = _REGISTEREVENTCOMMAND
_MESSAGE.fields_by_name['value12'].message_type = _REGISTEREVENTRESPONSE
_MESSAGE.fields_by_name['value13'].message_type = _REGISTERLISTENERCOMMAND
_MESSAGE.fields_by_name['value14'].message_type = _REGISTERLISTENERCOMMAND
_MESSAGE.fields_by_name['value15'].message_type = _DEREGISTERLISTENERCOMMAND
_MESSAGE.fields_by_name['value16'].message_type = _DEREGISTERLISTENERRESPONSE
_MESSAGE.fields_by_name['value17'].message_type = _FIREEVENTCOMMAND
_MESSAGE.fields_by_name['value19'].message_type = _REGISTEROBJECTCOMMAND
_MESSAGE.fields_by_name['value20'].message_type = _REGISTEROBJECTRESPONSE
_MESSAGE.fields_by_name['value21'].message_type = _WATCHOBJECTCOMMAND
_MESSAGE.fields_by_name['value22'].message_type = _WATCHOBJECTRESPONSE
_MESSAGE.fields_by_name['value23'].message_type = _UNWATCHOBJECTCOMMAND
_MESSAGE.fields_by_name['value24'].message_type = _UNWATCHOBJECTCOMMAND
_MESSAGE.fields_by_name['value25'].message_type = _SETOBJECTCOMMAND
_CALLFUNCTIONCOMMAND.fields_by_name['arguments'].message_type = _INSTANCE
_CALLFUNCTIONRESPONSE.fields_by_name['return_value'].message_type = _INSTANCE
_RUNFUNCTIONCOMMAND.fields_by_name['arguments'].message_type = _INSTANCE
_RUNFUNCTIONRESPONSE.fields_by_name['return_value'].message_type = _INSTANCE
_FIREEVENTCOMMAND.fields_by_name['arguments'].message_type = _INSTANCE
_REGISTEROBJECTCOMMAND.fields_by_name['value'].message_type = _INSTANCE
_WATCHOBJECTRESPONSE.fields_by_name['value'].message_type = _INSTANCE
_SETOBJECTCOMMAND.fields_by_name['value'].message_type = _INSTANCE

class MapEntry(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MAPENTRY

class StructEntry(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STRUCTENTRY

class Instance(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INSTANCE

class IntegerInstance(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INTEGERINSTANCE

class LongInstance(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LONGINSTANCE

class DoubleInstance(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DOUBLEINSTANCE

class StringInstance(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STRINGINSTANCE

class TimestampInstance(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TIMESTAMPINSTANCE

class NullInstance(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NULLINSTANCE

class ListInstance(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LISTINSTANCE

class MapInstance(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MAPINSTANCE

class StructInstance(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STRUCTINSTANCE

class ExceptionInstance(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EXCEPTIONINSTANCE

class BoolInstance(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BOOLINSTANCE

class Message(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MESSAGE

class RegisterInterfaceCommand(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REGISTERINTERFACECOMMAND

class RegisterInterfaceResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REGISTERINTERFACERESPONSE

class RegisterFunctionCommand(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REGISTERFUNCTIONCOMMAND

class RegisterFunctionResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REGISTERFUNCTIONRESPONSE

class CallFunctionCommand(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CALLFUNCTIONCOMMAND

class CallFunctionResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CALLFUNCTIONRESPONSE

class RunFunctionCommand(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RUNFUNCTIONCOMMAND

class RunFunctionResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RUNFUNCTIONRESPONSE

class ErrorResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ERRORRESPONSE

class RegisterEventCommand(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REGISTEREVENTCOMMAND

class RegisterEventResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REGISTEREVENTRESPONSE

class RegisterListenerCommand(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REGISTERLISTENERCOMMAND

class RegisterListenerResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REGISTERLISTENERRESPONSE

class DeregisterListenerCommand(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DEREGISTERLISTENERCOMMAND

class DeregisterListenerResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DEREGISTERLISTENERRESPONSE

class FireEventCommand(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FIREEVENTCOMMAND

class RegisterObjectCommand(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REGISTEROBJECTCOMMAND

class RegisterObjectResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REGISTEROBJECTRESPONSE

class WatchObjectCommand(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WATCHOBJECTCOMMAND

class WatchObjectResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WATCHOBJECTRESPONSE

class UnwatchObjectCommand(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _UNWATCHOBJECTCOMMAND

class UnwatchObjectResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _UNWATCHOBJECTRESPONSE

class SetObjectCommand(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SETOBJECTCOMMAND

