#!/bin/bash

# map contains lines where the first field is a mercurial rev and the second
# line is the corresponding filer rev
echo > map

hg log --repository source -r $1 --template "{node}\n" | while read hash; do
    print Source revision `hg log --template {rev} -r $hash`
    parents="`hg parents --repository source -r $hash --template "{node}\n"`"
    parent="`echo "$parents" | tail -1`"
    if [ -z "$parent" ]; then
        # No mercurial parents. Do a blank Filer checkout.
        filer checkout --repository target --working w
    else
        # Mercurial parents are present. Look up the corresponding Filer parent 
        filerparent="`cat map | grep "${hash}" | cut -d " " -f 2`"
done
